### ISSUE TITLE
Proposal: Add English version of README.md

### ISSUE THREAD

**Issue by qursor-dev** [g1879/DataRecorder#2]
Dear project maintainer,

I hope this message finds you well. I've been using your excellent DataRecorder tool and found it incredibly useful. To help broaden its reach and make it more accessible to non-Chinese speaking users, I would like to propose adding an English version of the README.md file.

Here's what I'm proposing:

1. Create an English translation of the existing README.md
2. Keep the current README.md in Chinese and add a new README.en.md file for the English version

Benefits of this addition:
- Increases the project's visibility to a wider, international audience
- Makes it easier for non-Chinese speakers to understand and use the tool
- Potentially attracts more contributors to the project

If you're open to this idea, I'd be happy to create the English translation and submit a pull request. Of course, I welcome any guidelines or preferences you might have regarding the translation or file structure.

Thank you for considering this proposal. I look forward to your thoughts on this matter.

Best regards,
SahutoL

**Comment by g1879** [comment]
谢谢。我英语不好，而且没有时间维护多种语言的文档。
文档网址：https://drissionpage.cn/DataRecorderDocs/
文档开源地址：https://github.com/g1879/DataRecorderDocs

**Comment by qursor-dev** [comment]
尊敬的项目维护者，

谢谢您的回复。我理解维护多种语言文档的挑战。感谢您提供文档的网址和开源地址，这对我非常有帮助。

如果以后您有任何需要帮助的地方，请随时告诉我。

再次感谢您的时间和努力。

祝好，

SahutoL
